#!/bin/sh

shell_enabled() {
    return 0
}

shell_run() {
    add_module_post_hook on_exit
    if [ "$bootparam_myshell" ]; then
	msg "$(grep ^PRETTY_NAME= /etc/os-release | cut -d= -f2) initramfs"
	/bin/bash
    fi
    return=${?}
}
